databases:
  - name: myfirstproject-db
    databaseName: myfirstproject
    user: myfirstproject_user
    plan: free

services:
  - type: web
    name: myfirstproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn MyfirstProject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myfirstproject-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
