databases:
  - name: myfirstproject-db
    databaseName: myfirstproject
    user: myfirstproject_user
    plan: free

services:
  - type: web
    name: myfirstproject
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn MyfirstProject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myfirstproject-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ACCUWEATHER_API_KEY
        value: zpka_9fda2bbaef414e97a4234daaa7437522_82653c5e
